### ISSUE TITLE
IPv6 Route Logic Fails

### ISSUE THREAD

**Issue by danehans** [Mirantis/kubeadm-dind-cluster#45]
I see the following error in a gce ipv6 deployment:

```
dind-cluster.sh: line 486: ip: command not found
```

Here is the related function in the script:
```
function dind::ensure-nat {
    if [[  ${IP_MODE} = "ipv6" ]]; then
        if ! docker ps | grep tayga >&/dev/null; then
            docker run -d --name tayga --hostname tayga --net kubeadm-dind-net --label mirantis.kubeadm_dind_cluster \
		   --sysctl net.ipv6.conf.all.disable_ipv6=0 --sysctl net.ipv6.conf.all.forwarding=1 \
		   --privileged=true --ip 172.18.0.200 --ip6 ${LOCAL_NAT64_SERVER} --dns ${REMOTE_DNS64_V4SERVER} --dns ${dns_server} \
		   -e TAYGA_CONF_PREFIX=${DNS64_PREFIX_CIDR} -e TAYGA_CONF_IPV4_ADDR=172.18.0.200 \
		   danehans/tayga:latest >/dev/null
	    # TODO Way to add route w/o sudo? Need to check/create, as "clean" may remove route
	    local route="$(ip route | egrep "^172.18.0.128/25")"
	    if [[ -z "${route}" ]]; then
		if [[ "${GCE_HOSTED}" = true ]]; then
		    docker-machine ssh k8s-dind sudo ip route add 172.18.0.128/25 via 172.18.0.200
		else
		    sudo ip route add 172.18.0.128/25 via 172.18.0.200
		fi
	    fi
	fi
    fi
}
```

I believe how the route is checked is dependent on $GCE_HOSTED. If $GCE_HOSTED = true, then:

```
docker-machine ssh k8s-dind sudo ip route | egrep "^172.18.0.128/25"
```

else:

```
ip route | egrep "^172.18.0.128/25"
```

cc @pmichali

**Comment by pmichali** [comment]
Did you ue the gce-setup-local.sh script?  It sets the GCE_HOSTED flag.  Now that the code is upstreamed, likely gcd-setup.sh also needs to do the same thing as ice-setup-local.sh.

P.S. I’m on PTO until after the 17th, and will have very limited internet access.

Regards,

Paul Michali (pcm)

**Comment by danehans** [comment]
I did use the gce-setup-local.sh script.

**Comment by ivan4th** [comment]
Note that k-d-c is supposed to be able to run against remote docker engines (case in point: CircleCI) and on on-Linux systems (e.g. Mac doesn't have `ip` command). So we need to either (preferably) somehow fix this (e.g. run the command using docker in host netns) or document the fact that IPv6 support is not compatible with Mac and remote docker.

**Comment by pmichali** [comment]
@danehans, If you used gce-setup-local.sh, then the GCE_HOSTED flag should be set. You can add "set -x" to dind-cluster.sh to see what is going on. Note: for gce-setup-local.sh, you need to set DIND_IMAGE and the BUILD_* env variables.  We should probably change gce-setup.sh, toset GCE_HOSTED to true.

@ivan4th, IIUC, this script is an example, and for GCE. For other hosting options, different settings may be needed.  For IPv6, we need a static route on the host, to the NAT66 server. It checks to see if one is there already, and if so, skips taking any action. If not, then it uses sudo to add the route. For GCE it uses docker-machine ssh to access the VM and add the route.

For other hosting options, the corresponding command would be needed to add the route.  For Mac, @danehans can confirm, but I don't think there is IPv6 support for docker, so it cannot be used as a hosting platform.

**Comment by ivan4th** [comment]
Well, what I tried to say is that proper way to add the route is probably using something like
`docker run --net=host --privileged "${busybox_image}" ip route add 172.18.0.128/25 via 172.18.0.200` instead of `sudo ip route add 172.18.0.128/25 via 172.18.0.200`. If docker engine runs on the same machine as `dind-cluster.sh` script, the effect will be the same, but it'll account for the case where `dind-cluster.sh` is run on another machine or cases like Mac Docker.

**Comment by pmichali** [comment]
Hi, I’m back from the Openstack Summit and PTO…

Thanks Ivan! I had an open TODO in the dins-cluster.sh, asking how to get around using sudo. This will work perfect.  I’ll update the script, add some changes for gcd-setup.sh, and revise the readme, based on updated PRs in flight. Right now, one in-flight PR that Rob is working on has some issues, so we need to get that resolved, so that I can test the latest.

Regards,

Paul Michali (pcm)

**Comment by pmichali** [comment]
Will push up a change soon that uses docker run command to set IP (along with other changes).

**Comment by lukaszo** [comment]
@danehans @pmichali is this issue fixed now?

**Comment by pmichali** [comment]
Yes.
